
positive_payload = {
    "CreateOrder": {
        "ShopRunnerOrder": 'false',
        "shippingConditions": 'null',
        "deliveryMode": "pickup",
        "orderPOType": "ZHYB",
        "reqeustDeliveryDate": 'null',
        "currencyISOCode": "USD",
        "baseStoreID": 'null',
        "partnerAddress": [
            {
                "Fax": 'null',
                "partnerCode": "WE",
                "patnerID": "9000919634",
                "firstName": "Kay",
                "lastName": "Hager",
                "pickupFirstName": 'null',
                "pickupLastName": 'null',
                "phoneticFirstName": 'null',
                "phoneticLastName": 'null',
                "postalCode": "92649",
                "city": "ORANGE Huntington Beach",
                "houseNumber": "15202",
                "regionISOCode": "CA",
                "countryISOCode": "US",
                "building": 'null',
                "appartment": 'null',
                "telNumber": "513-659-2881",
                "district": 'null',
                "title": "",
                "middleName": 'null',
                "middleName2": 'null',
                "poBox": 'null',
                "languageIsoCode": "EN",
                "street": "Graham Street",
                "email": "kayhager8@gmail.com",
                "isBopis": 'null',
                "pickupStoreName": 'null'
            },
            {
                "Fax": 'null',
                "partnerCode": "RE",
                "patnerID": "9000919634",
                "firstName": "Mary Kay",
                "lastName": "Hager",
                "pickupFirstName": 'null',
                "pickupLastName": 'null',
                "phoneticFirstName": 'null',
                "phoneticLastName": 'null',
                "postalCode": "92649",
                "city": "ORANGE Huntington Beach",
                "houseNumber": "15202",
                "regionISOCode": "CA",
                "countryISOCode": "US",
                "building": 'null',
                "appartment": 'null',
                "telNumber": "513-659-2881",
                "district": 'null',
                "title": "",
                "middleName": 'null',
                "middleName2": 'null',
                "poBox": 'null',
                "languageIsoCode": "EN",
                "street": "Graham Street",
                "email": "kayhager8@gmail.com",
                "isBopis": 'null',
                "pickupStoreName": 'null'
            },
            {
                "Fax": 'null',
                "partnerCode": "AG",
                "patnerID": "9000919634",
                "firstName": "Kay",
                "lastName": "Hager",
                "pickupFirstName": "Kay",
                "pickupLastName": "Hager",
                "phoneticFirstName": 'null',
                "phoneticLastName": 'null',
                "postalCode": "92649",
                "city": "ORANGE Huntington Beach",
                "houseNumber": "15202",
                "regionISOCode": "CA",
                "countryISOCode": "US",
                "building": 'null',
                "appartment": 'null',
                "telNumber": "513-659-2881",
                "district": 'null',
                "title": "",
                "middleName": 'null',
                "middleName2": 'null',
                "poBox": 'null',
                "languageIsoCode": "EN",
                "street": "Graham Street",
                "email": "kayhager8@gmail.com",
                "isBopis": "true",
                "pickupStoreName": "Kenwood Towne Centre"
            }
        ],
        "orderNumber": "7001578345",
        "worldpayOrderCode": 'null',
        "loyalityPointsApplied": "0",
        "cartLevelPotentialPoints": "375",
        "entries": [
            {
                "entryNumber": '0',
                "quantity": "1",
                "productCode": "1MU430_0BLK_M",
                "unitCode": "EA",
                "deliveryPriority": 'null',
                "productName": "TRAVEL PANT 2.0 ACTIVE PANT",
                "itemLevelDiscount": '24.98',
                "itemLevelOrderDiscount": 'null',
                "sourceId": "T027",
                "externalConfiguration": 'null',
                "grossPrice": '99.95',
                "taxAmmount": 'null',
                "grossPriceConditionType": "ZPR0",
                "itemLevelDiscountConditionType": "ZDS1",
                "itemLevelOrderDiscountConditionType": 'null',
                "taxConditions": [
                    {
                        "conditionType": "ZR1",
                        "conditionValue": '4.31'
                    },
                    {
                        "conditionType": "ZR2",
                        "conditionValue": '1.54'
                    }
                ],
                "itemLevelcartLevelPotentialPoints": '375',
                "itemLevelloyalityPointsApplied": 'null',
                "loyaltyPaymentConditionType": 'null',
                "loyaltyCartPotentialConditionType": "ZLPA",
                "pickupAddress": {
                    "Fax": 'null',
                    "partnerCode": "WP",
                    "patnerID": "9000919634",
                    "firstName": "Mary Kay",
                    "lastName": "Hager",
                    "pickupFirstName": "Kay",
                    "pickupLastName": "Hager",
                    "phoneticFirstName": 'null',
                    "phoneticLastName": 'null',
                    "postalCode": "45236",
                    "city": "Cincinnati",
                    "houseNumber": 'null',
                    "regionISOCode": "OH",
                    "countryISOCode": "US",
                    "building": "7875 Montgomery Rd",
                    "appartment": 'null',
                    "telNumber": "513-659-2881",
                    "district": 'null',
                    "title": 'null',
                    "middleName": 'null',
                    "middleName2": 'null',
                    "poBox": 'null',
                    "languageIsoCode": "EN",
                    "street": "Space 2221",
                    "email": "kayhager8@gmail.com",
                    "isBopis": "true",
                    "pickupStoreName": "Kenwood Towne Centre"
                },
                "tenderCouponApplied": 'null',
                "tenderCouponConditionType": 'null',
                "currencyISOCode": "USD"
            }
        ],
        "orderLevelDiscount": '0',
        "isShiptoStoreOrder": 'false',
        "bagPack": 'null',
        "boxPack": 'null',
        "shipToStoreNumber": 'null',
        "orderDate": "Mon Dec 04 12:47:10 PST 2023",
        "zterm": " ",
        "zcit": "MWEILVW541204",
        "organizations": [
            {
                "salesOrganization": "7300",
                "distributionChannel": "30",
                "division": "10"
            }
        ],
        "tenderCouponPrice": 'null',
        "loyaltyPaymentConditionType": 'null',
        "loyaltyCartPotentialConditionType": 'null',
        "itemLevelcartLevelPotentialPoints": 'null',
        "tenderCouponConditionType": 'null',
        "giftFrom": 'null',
        "giftTo": 'null',
        "giftMessage1": 'null',
        "giftMessage2": 'null',
        "giftMessage3": 'null',
        "isShopRunnerOrder": 'false',
        "shopRunnerReqDTO": 'null',
        "IsShipComplete": 'false',
        "paymentDetail": [
            {
                "paymentProvider": "paymetric",
                "requestToken": "01274Z,80.8200,2034420368",
                "startMonth": 'null',
                "startYear": 'null',
                "expiryMonth": "3",
                "expiryYear": "2027",
                "subscriptionId": "2034420357",
                "accountHolderName": "Mary Kay Hager",
                "cardType": "master",
                "requestID": "2034420357",
                "paypalID": 'null',
                "paypalTransactionID": 'null',
                "cardNumber": "-E803-9927-02XM4QA9N9K70Z",
                "authTM": "Mon Dec 04 20:45:39 PST 2023",
                "paypalIDConditionType": 'null',
                "xipayConditionType": 'null',
                "billingAddress": 'null'
            }
        ]
    }
}

wrong_tel_number_payload = {
    "CreateOrder": {
        "ShopRunnerOrder": 'false',
        "shippingConditions": 'null',
        "deliveryMode": "pickup",
        "orderPOType": "ZHYB",
        "reqeustDeliveryDate": 'null',
        "currencyISOCode": "USD",
        "baseStoreID": 'null',
        "partnerAddress": [
            {
                "Fax": 'null',
                "partnerCode": "WE",
                "patnerID": "9000919634",
                "firstName": "Kay",
                "lastName": "Hager",
                "pickupFirstName": 'null',
                "pickupLastName": 'null',
                "phoneticFirstName": 'null',
                "phoneticLastName": 'null',
                "postalCode": "92649",
                "city": "ORANGE Huntington Beach",
                "houseNumber": "15202",
                "regionISOCode": "CA",
                "countryISOCode": "US",
                "building": 'null',
                "appartment": 'null',
                "telNumber": "513-659-2881",
                "district": 'null',
                "title": "",
                "middleName": 'null',
                "middleName2": 'null',
                "poBox": 'null',
                "languageIsoCode": "EN",
                "street": "Graham Street",
                "email": "kayhager8@gmail.com",
                "isBopis": 'null',
                "pickupStoreName": 'null'
            },
            {
                "Fax": 'null',
                "partnerCode": "RE",
                "patnerID": "9000919634",
                "firstName": "Mary Kay",
                "lastName": "Hager",
                "pickupFirstName": 'null',
                "pickupLastName": 'null',
                "phoneticFirstName": 'null',
                "phoneticLastName": 'null',
                "postalCode": "92649",
                "city": "ORANGE Huntington Beach",
                "houseNumber": "15202",
                "regionISOCode": "CA",
                "countryISOCode": "US",
                "building": 'null',
                "appartment": 'null',
                "telNumber": "513-659-2881",
                "district": 'null',
                "title": "",
                "middleName": 'null',
                "middleName2": 'null',
                "poBox": 'null',
                "languageIsoCode": "EN",
                "street": "Graham Street",
                "email": "kayhager8@gmail.com",
                "isBopis": 'null',
                "pickupStoreName": 'null'
            },
            {
                "Fax": 'null',
                "partnerCode": "AG",
                "patnerID": "9000919634",
                "firstName": "Kay",
                "lastName": "Hager",
                "pickupFirstName": "Kay",
                "pickupLastName": "Hager",
                "phoneticFirstName": 'null',
                "phoneticLastName": 'null',
                "postalCode": "92649",
                "city": "ORANGE Huntington Beach",
                "houseNumber": "15202",
                "regionISOCode": "CA",
                "countryISOCode": "US",
                "building": 'null',
                "appartment": 'null',
                "telNumber": "000-000-0000",
                "district": 'null',
                "title": "",
                "middleName": 'null',
                "middleName2": 'null',
                "poBox": 'null',
                "languageIsoCode": "EN",
                "street": "Graham Street",
                "email": "kayhager8@gmail.com",
                "isBopis": "true",
                "pickupStoreName": "Kenwood Towne Centre"
            }
        ],
        "orderNumber": "7001578345",
        "worldpayOrderCode": 'null',
        "loyalityPointsApplied": "0",
        "cartLevelPotentialPoints": "375",
        "entries": [
            {
                "entryNumber": '0',
                "quantity": "1",
                "productCode": "1MU430_0BLK_M",
                "unitCode": "EA",
                "deliveryPriority": 'null',
                "productName": "TRAVEL PANT 2.0 ACTIVE PANT",
                "itemLevelDiscount": '24.98',
                "itemLevelOrderDiscount": 'null',
                "sourceId": "T027",
                "externalConfiguration": 'null',
                "grossPrice": '99.95',
                "taxAmmount": 'null',
                "grossPriceConditionType": "ZPR0",
                "itemLevelDiscountConditionType": "ZDS1",
                "itemLevelOrderDiscountConditionType": 'null',
                "taxConditions": [
                    {
                        "conditionType": "ZR1",
                        "conditionValue": '4.31'
                    },
                    {
                        "conditionType": "ZR2",
                        "conditionValue": '1.54'
                    }
                ],
                "itemLevelcartLevelPotentialPoints": '375',
                "itemLevelloyalityPointsApplied": 'null',
                "loyaltyPaymentConditionType": 'null',
                "loyaltyCartPotentialConditionType": "ZLPA",
                "pickupAddress": {
                    "Fax": 'null',
                    "partnerCode": "WP",
                    "patnerID": "9000919634",
                    "firstName": "Mary Kay",
                    "lastName": "Hager",
                    "pickupFirstName": "Kay",
                    "pickupLastName": "Hager",
                    "phoneticFirstName": 'null',
                    "phoneticLastName": 'null',
                    "postalCode": "45236",
                    "city": "Cincinnati",
                    "houseNumber": 'null',
                    "regionISOCode": "OH",
                    "countryISOCode": "US",
                    "building": "7875 Montgomery Rd",
                    "appartment": 'null',
                    "telNumber": "513-659-2881",
                    "district": 'null',
                    "title": 'null',
                    "middleName": 'null',
                    "middleName2": 'null',
                    "poBox": 'null',
                    "languageIsoCode": "EN",
                    "street": "Space 2221",
                    "email": "kayhager8@gmail.com",
                    "isBopis": "true",
                    "pickupStoreName": "Kenwood Towne Centre"
                },
                "tenderCouponApplied": 'null',
                "tenderCouponConditionType": 'null',
                "currencyISOCode": "USD"
            }
        ],
        "orderLevelDiscount": '0',
        "isShiptoStoreOrder": 'false',
        "bagPack": 'null',
        "boxPack": 'null',
        "shipToStoreNumber": 'null',
        "orderDate": "Mon Dec 04 12:47:10 PST 2023",
        "zterm": " ",
        "zcit": "MWEILVW541204",
        "organizations": [
            {
                "salesOrganization": "7300",
                "distributionChannel": "30",
                "division": "10"
            }
        ],
        "tenderCouponPrice": 'null',
        "loyaltyPaymentConditionType": 'null',
        "loyaltyCartPotentialConditionType": 'null',
        "itemLevelcartLevelPotentialPoints": 'null',
        "tenderCouponConditionType": 'null',
        "giftFrom": 'null',
        "giftTo": 'null',
        "giftMessage1": 'null',
        "giftMessage2": 'null',
        "giftMessage3": 'null',
        "isShopRunnerOrder": 'false',
        "shopRunnerReqDTO": 'null',
        "IsShipComplete": 'false',
        "paymentDetail": [
            {
                "paymentProvider": "paymetric",
                "requestToken": "01274Z,80.8200,2034420368",
                "startMonth": 'null',
                "startYear": 'null',
                "expiryMonth": "3",
                "expiryYear": "2027",
                "subscriptionId": "2034420357",
                "accountHolderName": "Mary Kay Hager",
                "cardType": "master",
                "requestID": "2034420357",
                "paypalID": 'null',
                "paypalTransactionID": 'null',
                "cardNumber": "-E803-9927-02XM4QA9N9K70Z",
                "authTM": "Mon Dec 04 20:45:39 PST 2023",
                "paypalIDConditionType": 'null',
                "xipayConditionType": 'null',
                "billingAddress": 'null'
            }
        ]
    }
}
