name: Pytest Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Create Report Directory
        run: mkdir -p $GITHUB_WORKSPACE/report

      - name: Run pytest
        run: 
          pytest test_JP_B2C_User_Reg.py -v -s --html=report.html
          
      - name: Move the Report file
        run: mv report.html $GITHUB_WORKSPACE/report
      
      - name: Upload HTML Report as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report/report.html

     

          

     
         
      # You can add more steps here, such as linting or other checks
